### PR TITLE
Add NotCheckpointSafe to prevent JVMCheckpointException/deadlock

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Annotated `java.lang.ClassValue.initializeMap()`, `java.lang.invoke.ClassSpecializer.findSpecies()` & `java.util.concurrent.ConcurrentHashMap.computeIfAbsent()` with `NotCheckpointSafe`.

Related https://github.com/eclipse-openj9/openj9/issues/15568
Depends https://github.com/eclipse-openj9/openj9/pull/15593

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
Jenkins test sanity.functional zlinux jdk17 depends eclipse-openj9/openj9#15593

**Comment by tajila** [comment]
Can you also add the annotation to  `sun.nio.cs.StandardCharsets::charsetForName`

```
    public final Charset charsetForName(String charsetName) {
        synchronized (this) {
            return lookup(charsetName);
        }
    }
```

**Comment by JasonFengJ9** [comment]
> Can you also add the annotation to sun.nio.cs.StandardCharsets::charsetForName

Sure thing, is there an issue or stacktrace suggesting this is a problematic method?

**Comment by tajila** [comment]
From a slack convo:

```
3XMTHREADBLOCK     Blocked on: sun/nio/cs/StandardCharsets@0x0000000083C867B8 Owned by: "Default Executor-thread-3" (J9VMThread:0x0000000000713800, java/lang/Thread:0x000000008463B920)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=69632 (0x11000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at sun/nio/cs/StandardCharsets.charsetForName(StandardCharsets.java:1339)
4XESTACKTRACE                at java/nio/charset/Charset.lookup2(Charset.java:473)
4XESTACKTRACE                at java/nio/charset/Charset.lookup(Charset.java:462(Compiled Code))
4XESTACKTRACE                at java/nio/charset/Charset.isSupported(Charset.java:503(Compiled Code))
4XESTACKTRACE                at java/lang/StringCoding.lookupCharset(StringCoding.java:101(Compiled Code))
4XESTACKTRACE                at java/lang/StringCoding.encode(StringCoding.java:425(Compiled Code))
4XESTACKTRACE                at java/lang/String.getBytes(String.java:1863(Compiled Code))
4XESTACKTRACE                at java/io/FileInputStream.open0(Native Method)
4XESTACKTRACE                at java/io/FileInputStream.open(FileInputStream.java:219)
4XESTACKTRACE                at java/io/FileInputStream.<init>(FileInputStream.java:157)
4XESTACKTRACE                at java/io/FileInputStream.<init>(FileInputStream.java:112)
4XESTACKTRACE                at java/io/FileReader.<init>(FileReader.java:60)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport.lambda$registerRestoreEnvVariables$4(CRIUSupport.java:490)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport$$Lambda$207/0x0000000000000000.run(Bytecode PC:4)
4XESTACKTRACE                at org/eclipse/openj9/criu/J9InternalCheckpointHookAPI$J9InternalCheckpointHook.runHook(J9InternalCheckpointHookAPI.java:116)
4XESTACKTRACE                at org/eclipse/openj9/criu/J9InternalCheckpointHookAPI.runHooks(J9InternalCheckpointHookAPI.java:80)
4XESTACKTRACE                at org/eclipse/openj9/criu/J9InternalCheckpointHookAPI.runPostRestoreHooks(J9InternalCheckpointHookAPI.java:97)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport.checkpointJVMImpl(Native Method)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport.checkpointJVM(CRIUSupport.java:580)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/openj9/ExecuteCRIU_OpenJ9.dump(ExecuteCRIU_OpenJ9.java:56)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.checkpoint(CheckpointImpl.java:375)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.checkpointOrExitOnFailure(CheckpointImpl.java:314)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.check(CheckpointImpl.java:309)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager$$Lambda$190/0x0000000000000000.accept(Bytecode PC:6)
4XESTACKTRACE                at java/util/ArrayList.forEach(ArrayList.java:1541)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager.checkServerReady(FeatureManager.java:824)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager.update(FeatureManager.java:787)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager.processFeatureChanges(FeatureManager.java:887)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager$1.run(FeatureManager.java:673)
4XESTACKTRACE                at com/ibm/ws/threading/internal/ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:835)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               protectedBacktrace+0x12 (0x00007F74D0626782 [libj9prt29.so+0x26782])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007F74D062AF43 [libj9prt29.so+0x2af43])
4XENATIVESTACK               omrintrospect_backtrace_thread_raw+0xbf (0x00007F74D0626C7F [libj9prt29.so+0x26c7f])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007F74D062AF43 [libj9prt29.so+0x2af43])
4XENATIVESTACK               omrintrospect_backtrace_thread+0x70 (0x00007F74D0626640 [libj9prt29.so+0x26640])
4XENATIVESTACK               upcall_handler+0x26f (0x00007F74D062787F [libj9prt29.so+0x2787f])
4XENATIVESTACK                (0x00007F74D1E1A520 [libc.so.6+0x42520])
4XENATIVESTACK                (0x00007F74D1E69197 [libc.so.6+0x91197])
4XENATIVESTACK               pthread_cond_timedwait+0x23b (0x00007F74D1E6BF1B [libc.so.6+0x93f1b])
4XENATIVESTACK               omrthread_monitor_wait_timed+0x702 (0x00007F74D020CDE2 [libj9thr29.so+0xcde2])
4XENATIVESTACK               objectMonitorEnterBlocking+0x40c (0x00007F74D0A6BE9C [libj9vm29.so+0x6be9c])
4XENATIVESTACK               _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x156cf (0x00007F74D0AA8C4F [libj9vm29.so+0xa8c4f])
4XENATIVESTACK               bytecodeLoopCompressed+0xad (0x00007F74D0A9356D [libj9vm29.so+0x9356d])
4XENATIVESTACK                (0x00007F74D0B4E362 [libj9vm29.so+0x14e362])
```

and

```
3XMTHREADINFO      "Default Executor-thread-3" J9VMThread:0x0000000000713800, omrthread_t:0x00007F743406C180, java/lang/Thread:0x000000008463B920, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x2E, isDaemon:true)
3XMJAVALTHRCCL            org/eclipse/osgi/internal/framework/ContextFinder(0x0000000084066B10)
3XMTHREADINFO1            (native thread ID:0x21430D, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00200000)
3XMTHREADINFO2            (native stack address range from:0x00007F748FF3E000, to:0x00007F748FF7E000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.010866114 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Class.forNameImpl(Native Method)
4XESTACKTRACE                at java/lang/Class.forName(Class.java:417)
4XESTACKTRACE                at sun/nio/cs/StandardCharsets.lookup(StandardCharsets.java:1322)
4XESTACKTRACE                at sun/nio/cs/StandardCharsets.charsetForName(StandardCharsets.java:1340)
5XESTACKTRACE                   (entered lock: sun/nio/cs/StandardCharsets@0x0000000083C867B8, entry count: 1)
4XESTACKTRACE                at java/nio/charset/Charset.lookup2(Charset.java:473)
4XESTACKTRACE                at java/nio/charset/Charset.lookup(Charset.java:462(Compiled Code))
4XESTACKTRACE                at java/nio/charset/Charset.forName(Charset.java:526(Compiled Code))
4XESTACKTRACE                at com/sun/org/apache/xml/internal/serializer/Encodings$EncodingInfos.findCharsetNameFor(Encodings.java:401)
4XESTACKTRACE                at com/sun/org/apache/xml/internal/serializer/Encodings$EncodingInfos.findCharsetNameFor(Encodings.java:437)
4XESTACKTRACE                at com/sun/org/apache/xml/internal/serializer/Encodings$EncodingInfos.loadEncodingInfo(Encodings.java:465)
4XESTACKTRACE                at com/sun/org/apache/xml/internal/serializer/Encodings$EncodingInfos.<init>(Encodings.java:323)
4XESTACKTRACE                at com/sun/org/apache/xml/internal/serializer/Encodings.<clinit>(Encodings.java:579)
4XESTACKTRACE                at com/sun/org/apache/xml/internal/serializer/ToStream.<init>(ToStream.java:134)
4XESTACKTRACE                at com/sun/org/apache/xml/internal/serializer/ToXMLStream.<init>(ToXMLStream.java:65)
4XESTACKTRACE                at com/sun/org/apache/xalan/internal/xsltc/runtime/output/TransletOutputHandlerFactory.getSerializationHandler(TransletOutputHandlerFactory.java:164)
4XESTACKTRACE                at com/sun/org/apache/xalan/internal/xsltc/trax/TransformerImpl.getOutputHandler(TransformerImpl.java:466)
4XESTACKTRACE                at com/sun/org/apache/xalan/internal/xsltc/trax/TransformerImpl.transform(TransformerImpl.java:355)
4XESTACKTRACE                at com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.generateXML(PluginGenerator.java:797)
5XESTACKTRACE                   (entered lock: com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator@0x00000000850A81E0, entry count: 1)
4XESTACKTRACE                at com/ibm/ws/webcontainer/osgi/mbeans/GeneratePluginConfigMBean.generatePluginConfig(GeneratePluginConfigMBean.java:165)
5XESTACKTRACE                   (entered lock: java/lang/Object@0x0000000084FBB858, entry count: 1)
5XESTACKTRACE                   (entered lock: com/ibm/ws/webcontainer/osgi/mbeans/GeneratePluginConfigMBean@0x0000000084FD9840, entry count: 1)
4XESTACKTRACE                at com/ibm/ws/webcontainer/osgi/mbeans/GeneratePluginConfigMBean.generatePluginConfig(GeneratePluginConfigMBean.java:269)
4XESTACKTRACE                at com/ibm/ws/webserver/plugin/runtime/listeners/GeneratePluginConfigListener$1.run(GeneratePluginConfigListener.java:281)
4XESTACKTRACE                at com/ibm/ws/threading/internal/ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
4XESTACKTRACE                at java/util/concurrent/Executors$RunnableAdapter.call(Executors.java:515(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/FutureTask.run(FutureTask.java:264(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:835)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               protectedBacktrace+0x12 (0x00007F74D0626782 [libj9prt29.so+0x26782])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007F74D062AF43 [libj9prt29.so+0x2af43])
4XENATIVESTACK               omrintrospect_backtrace_thread_raw+0xbf (0x00007F74D0626C7F [libj9prt29.so+0x26c7f])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007F74D062AF43 [libj9prt29.so+0x2af43])
4XENATIVESTACK               omrintrospect_backtrace_thread+0x70 (0x00007F74D0626640 [libj9prt29.so+0x26640])
4XENATIVESTACK               upcall_handler+0x26f (0x00007F74D062787F [libj9prt29.so+0x2787f])
4XENATIVESTACK                (0x00007F74D1E1A520 [libc.so.6+0x42520])
4XENATIVESTACK                (0x00007F74D1E69195 [libc.so.6+0x91195])
4XENATIVESTACK               pthread_cond_wait+0x211 (0x00007F74D1E6BAC1 [libc.so.6+0x93ac1])
4XENATIVESTACK               omrthread_monitor_wait+0x287 (0x00007F74D02089E7 [libj9thr29.so+0x89e7])
4XENATIVESTACK               internalAcquireVMAccessNoMutexWithMask+0x20c (0x00007F74D0A84F2C [libj9vm29.so+0x84f2c])
4XENATIVESTACK               javaCheckAsyncMessages+0xe0 (0x00007F74D0A17B90 [libj9vm29.so+0x17b90])
4XENATIVESTACK               _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x209 (0x00007F74D0A93789 [libj9vm29.so+0x93789])
4XENATIVESTACK               bytecodeLoopCompressed+0xad (0x00007F74D0A9356D [libj9vm29.so+0x9356d])
4XENATIVESTACK                (0x00007F74D0B4E362 [libj9vm29.so+0x14e362])
```

**Comment by JasonFengJ9** [comment]
Annotated `sun.nio.cs.StandardCharsets::charsetForName`.

This PR depends on https://github.com/eclipse-openj9/openj9/pull/15593 in which review comment is to be addressed.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
One more spot in java.lang.ClassValue::initializeMap

```
3XMTHREADINFO      "Executor Service Control Timer" J9VMThread:0x00000000006A9A00, omrthread_t:0x00007FD66401E860, java/lang/Thread:0x000000008427C2D8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x29, isDaemon:true)
3XMJAVALTHRCCL            org/eclipse/osgi/internal/framework/ContextFinder(0x0000000083F80450)
3XMTHREADINFO1            (native thread ID:0x11657D, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00200081)
3XMTHREADINFO2            (native stack address range from:0x00007FD6E5CBF000, to:0x00007FD6E5CFF000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.019966811 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/util/WeakHashMap.<init>(WeakHashMap.java:219(Compiled Code))
4XESTACKTRACE                at java/util/WeakHashMap.<init>(WeakHashMap.java:241(Compiled Code))
4XESTACKTRACE                at java/lang/ClassValue$ClassValueMap.<init>(ClassValue.java:429)
4XESTACKTRACE                at java/lang/ClassValue.initializeMap(ClassValue.java:380)
5XESTACKTRACE                   (entered lock: java/lang/Object@0x0000000083C8B558, entry count: 1)
4XESTACKTRACE                at java/lang/ClassValue.getMap(ClassValue.java:370)
4XESTACKTRACE                at java/lang/ClassValue.getFromHashMap(ClassValue.java:221)
4XESTACKTRACE                at java/lang/ClassValue.getFromBackup(ClassValue.java:210)
4XESTACKTRACE                at java/lang/ClassValue.get(ClassValue.java:116(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/HandleCache.getConstructorCache(HandleCache.java:130)
4XESTACKTRACE                at java/lang/invoke/MethodHandles$Lookup.unreflectConstructor(MethodHandles.java:1206)
4XESTACKTRACE                at com/ibm/java/lang/management/internal/ThreadMXBeanImpl$1.run(ThreadMXBeanImpl.java:803)
4XESTACKTRACE                at com/ibm/java/lang/management/internal/ThreadMXBeanImpl$1.run(ThreadMXBeanImpl.java:795)
4XESTACKTRACE                at java/security/AccessController.doPrivileged(AccessController.java:691(Compiled Code))
4XESTACKTRACE                at com/ibm/java/lang/management/internal/ThreadMXBeanImpl.getThreadInfoConstructorHandle(ThreadMXBeanImpl.java:795)
4XESTACKTRACE                at com/ibm/java/lang/management/internal/ThreadMXBeanImpl.<clinit>(ThreadMXBeanImpl.java:49)
4XESTACKTRACE                at com/ibm/lang/management/internal/PlatformMBeanProvider.<clinit>(PlatformMBeanProvider.java:76)
4XESTACKTRACE                at jdk/internal/reflect/NativeConstructorAccessorImpl.newInstance0(Native Method)
4XESTACKTRACE                at jdk/internal/reflect/NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62(Compiled Code))
4XESTACKTRACE                at jdk/internal/reflect/DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Constructor.newInstance(Constructor.java:490(Compiled Code))
4XESTACKTRACE                at java/util/ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
4XESTACKTRACE                at java/util/ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
4XESTACKTRACE                at java/util/ServiceLoader$3.next(ServiceLoader.java:1395)
4XESTACKTRACE                at java/lang/Iterable.forEach(Iterable.java:74)
4XESTACKTRACE                at java/lang/management/ManagementFactory$PlatformMBeanFinder.lambda$static$0(ManagementFactory.java:926)
4XESTACKTRACE                at java/lang/management/ManagementFactory$PlatformMBeanFinder$$Lambda$135/0x0000000000000000.run(Bytecode PC:0)
4XESTACKTRACE                at java/security/AccessController.doPrivileged(AccessController.java:886)
4XESTACKTRACE                at java/lang/management/ManagementFactory$PlatformMBeanFinder.<clinit>(ManagementFactory.java:922)
4XESTACKTRACE                at java/lang/management/ManagementFactory.getPlatformMXBean(ManagementFactory.java:684)
4XESTACKTRACE                at java/lang/management/ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:388)
4XESTACKTRACE                at com/ibm/ws/kernel/service/util/CpuInfo.createCpuInfoAccessor(CpuInfo.java:294)
5XESTACKTRACE                   (entered lock: com/ibm/ws/kernel/service/util/CpuInfo@0x000000008425DB10, entry count: 1)
4XESTACKTRACE                at com/ibm/ws/kernel/service/util/CpuInfo.getProcessCPU(CpuInfo.java:156)
4XESTACKTRACE                at com/ibm/ws/kernel/service/util/CpuInfo.getJavaCpuUsage(CpuInfo.java:273)
5XESTACKTRACE                   (entered lock: com/ibm/ws/threading/internal/ThreadPoolController@0x0000000084318EC0, entry count: 1)
4XESTACKTRACE                at com/ibm/ws/threading/internal/ThreadPoolController.evaluateInterval(ThreadPoolController.java:1307)
4XESTACKTRACE                at com/ibm/ws/threading/internal/IntervalTask.run(ThreadPoolController.java:1996)
4XESTACKTRACE                at java/util/TimerThread.mainLoop(Timer.java:586)
4XESTACKTRACE                at java/util/TimerThread.run(Timer.java:526)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               protectedBacktrace+0x12 (0x00007FD70A426CF2 [libj9prt29.so+0x26cf2])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007FD70A42B4B3 [libj9prt29.so+0x2b4b3])
4XENATIVESTACK               omrintrospect_backtrace_thread_raw+0xbf (0x00007FD70A4271EF [libj9prt29.so+0x271ef])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007FD70A42B4B3 [libj9prt29.so+0x2b4b3])
4XENATIVESTACK               omrintrospect_backtrace_thread+0x70 (0x00007FD70A426BB0 [libj9prt29.so+0x26bb0])
4XENATIVESTACK               upcall_handler+0x26f (0x00007FD70A427DEF [libj9prt29.so+0x27def])
4XENATIVESTACK                (0x00007FD70BC1A520 [libc.so.6+0x42520])
4XENATIVESTACK                (0x00007FD70BC69195 [libc.so.6+0x91195])
4XENATIVESTACK               pthread_cond_wait+0x211 (0x00007FD70BC6BAC1 [libc.so.6+0x93ac1])
4XENATIVESTACK               omrthread_monitor_wait+0x287 (0x00007FD70A0089E7 [libj9thr29.so+0x89e7])
4XENATIVESTACK               internalAcquireVMAccessNoMutexWithMask+0x20c (0x00007FD70A884FAC [libj9vm29.so+0x84fac])
4XENATIVESTACK               javaCheckAsyncMessages+0xe0 (0x00007FD70A817C00 [libj9vm29.so+0x17c00])
4XENATIVESTACK               old_slow_jitCheckAsyncMessages+0x85 (0x00007FD7039596A5 [libj9jit29.so+0x9596a5])
4XENATIVESTACK                (0x00007FD7039713BB [libj9jit29.so+0x9713bb])
```
```
3XMTHREADINFO      "Default Executor-thread-1" J9VMThread:0x0000000000705E00, omrthread_t:0x00007FD67001BC60, java/lang/Thread:0x000000008427C3B8, state:B, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x2C, isDaemon:true)
3XMJAVALTHRCCL            org/eclipse/osgi/internal/framework/ContextFinder(0x0000000083F80450)
3XMTHREADINFO1            (native thread ID:0x11657F, native priority:0x5, native policy:UNKNOWN, vmstate:B, vm thread flags:0x00000281)
3XMTHREADINFO2            (native stack address range from:0x00007FD6E5C3D000, to:0x00007FD6E5C7D000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.308877813 secs, current category="Application"
3XMTHREADBLOCK     Blocked on: java/lang/Object@0x0000000083C8B558 Owned by: "Executor Service Control Timer" (J9VMThread:0x00000000006A9A00, java/lang/Thread:0x000000008427C2D8)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=872456 (0xD5008)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/ClassValue.initializeMap(ClassValue.java:377)
4XESTACKTRACE                at java/lang/ClassValue.getMap(ClassValue.java:370)
4XESTACKTRACE                at java/lang/ClassValue.getFromHashMap(ClassValue.java:221)
4XESTACKTRACE                at java/lang/ClassValue.getFromBackup(ClassValue.java:210)
4XESTACKTRACE                at java/lang/ClassValue.get(ClassValue.java:116(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/HandleCache.getStaticCache(HandleCache.java:124(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/MethodHandles$Lookup.findStatic(MethodHandles.java:644(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/MethodHandleResolver.sendResolveMethodHandle(MethodHandleResolver.java:312)
4XESTACKTRACE                at java/lang/invoke/MethodHandleResolver.getCPMethodHandleAt(Native Method)
4XESTACKTRACE                at java/lang/invoke/MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:465)
4XESTACKTRACE                at java/lang/invoke/MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:229(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/app/manager/internal/ApplicationConfigurator.restore(ApplicationConfigurator.java:2092)
5XESTACKTRACE                   (entered lock: com/ibm/ws/app/manager/internal/ApplicationConfigurator@0x0000000084CE4210, entry count: 1)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl$$Lambda$177/0x0000000000000000.accept(Bytecode PC:6)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.callHooks(CheckpointImpl.java:515)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.restore(CheckpointImpl.java:537)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.lambda$checkpoint$7(CheckpointImpl.java:376)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl$$Lambda$170/0x0000000000000000.run(Bytecode PC:8)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport.lambda$registerPostRestoreHook$2(CRIUSupport.java:445)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport$$Lambda$172/0x0000000000000000.run(Bytecode PC:4)
4XESTACKTRACE                at org/eclipse/openj9/criu/J9InternalCheckpointHookAPI$J9InternalCheckpointHook.runHook(J9InternalCheckpointHookAPI.java:116)
4XESTACKTRACE                at org/eclipse/openj9/criu/J9InternalCheckpointHookAPI.runHooks(J9InternalCheckpointHookAPI.java:80)
5XESTACKTRACE                   (entered lock: org/eclipse/openj9/criu/CRIUSupport@0x00000000FEB8FB28, entry count: 1)
4XESTACKTRACE                at org/eclipse/openj9/criu/J9InternalCheckpointHookAPI.runPostRestoreHooks(J9InternalCheckpointHookAPI.java:97)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport.checkpointJVMImpl(Native Method)
4XESTACKTRACE                at org/eclipse/openj9/criu/CRIUSupport.checkpointJVM(CRIUSupport.java:589)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/openj9/ExecuteCRIU_OpenJ9.dump(ExecuteCRIU_OpenJ9.java:56)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.checkpoint(CheckpointImpl.java:375)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.checkpointOrExitOnFailure(CheckpointImpl.java:314)
4XESTACKTRACE                at io/openliberty/checkpoint/internal/CheckpointImpl.check(CheckpointImpl.java:309)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager$$Lambda$157/0x0000000000000000.accept(Bytecode PC:6)
4XESTACKTRACE                at java/util/ArrayList.forEach(ArrayList.java:1541)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager.checkServerReady(FeatureManager.java:824)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager.update(FeatureManager.java:787)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager.processFeatureChanges(FeatureManager.java:887)
4XESTACKTRACE                at com/ibm/ws/kernel/feature/internal/FeatureManager$1.run(FeatureManager.java:673)
4XESTACKTRACE                at com/ibm/ws/threading/internal/ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:844)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               protectedBacktrace+0x12 (0x00007FD70A426CF2 [libj9prt29.so+0x26cf2])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007FD70A42B4B3 [libj9prt29.so+0x2b4b3])
4XENATIVESTACK               omrintrospect_backtrace_thread_raw+0xbf (0x00007FD70A4271EF [libj9prt29.so+0x271ef])
4XENATIVESTACK               omrsig_protect+0x1e3 (0x00007FD70A42B4B3 [libj9prt29.so+0x2b4b3])
4XENATIVESTACK               omrintrospect_backtrace_thread+0x70 (0x00007FD70A426BB0 [libj9prt29.so+0x26bb0])
4XENATIVESTACK               upcall_handler+0x26f (0x00007FD70A427DEF [libj9prt29.so+0x27def])
4XENATIVESTACK                (0x00007FD70BC1A520 [libc.so.6+0x42520])
4XENATIVESTACK                (0x00007FD70BC69195 [libc.so.6+0x91195])
4XENATIVESTACK               pthread_cond_wait+0x211 (0x00007FD70BC6BAC1 [libc.so.6+0x93ac1])
4XENATIVESTACK               omrthread_monitor_wait+0x287 (0x00007FD70A0089E7 [libj9thr29.so+0x89e7])
4XENATIVESTACK               internalAcquireVMAccessNoMutexWithMask+0x20c (0x00007FD70A884FAC [libj9vm29.so+0x84fac])
4XENATIVESTACK               internalAcquireVMAccess+0x63 (0x00007FD70A884C53 [libj9vm29.so+0x84c53])
4XENATIVESTACK               objectMonitorEnterBlocking+0x8a3 (0x00007FD70A86C393 [libj9vm29.so+0x6c393])
4XENATIVESTACK               _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x156df (0x00007FD70A8A8E2F [libj9vm29.so+0xa8e2f])
4XENATIVESTACK               bytecodeLoopCompressed+0xad (0x00007FD70A89373D [libj9vm29.so+0x9373d])
4XENATIVESTACK                (0x00007FD70A94E5D2 [libj9vm29.so+0x14e5d2])
```

**Comment by JasonFengJ9** [comment]
Annotated follow classes w/ `NotCheckpointSafe`
```
src/java.base/share/classes/java/lang/ClassValue.java
src/java.base/share/classes/java/lang/invoke/ClassSpecializer.java
src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java
```

`sun.nio.cs.StandardCharsets::charsetForName` will have to be handled differently probably in a separated PR since it is generated after current JPP process.

**Comment by JasonFengJ9** [comment]
Jenkins test sanity.functional xlinuxcriu jdk17 depends eclipse-openj9/openj9#15593

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal/7/tapResults/
```
Testing: Create Criu Checkpoint Image once and no restore - TestSingleThreadModeCheckpointException

>> Success condition was not found: [Output match: TestSingleThreadModeCheckpointException: PASSED]

Testing: Create and Restore Criu Checkpoint Image once - TestSingleThreadModeRestoreException

>> Success condition was not found: [Output match: org.eclipse.openj9.criu.RestoreException: Exception thrown when running user post-restore]
```
It appears these tests are obsoleted by `NotCheckpointSafe` annotation, will open a PR to disable them.

**Comment by JasonFengJ9** [comment]
Superseded by https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/128.

**Pull request closed without merging**
