### PR TITLE
[JEP389/412] Implement the CLinker upcall handler in Java17

### PR DESCRIPTION
**Pull request by ChengJin01**
The changes aim to enable the CLinker upcall handler
to support primitives and struct by invoking the code
in ProgrammableUpcallHandler implemented in OpenJ9.
In addition, the changes also include the code specific
to the default library loading on AIX.

Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
The Java17 specific changes (enabling upcall on Power /pretty much the same code as https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/57 in Java 18 with the updated APIs) in OpenJDK belong to the issue intended for the upcall work at #15068.
Note:
The PR depends on the PR at https://github.com/eclipse-openj9/openj9/pull/15069 and the native code (PRs) in [Design and Implementation of Foreign Linker API: Upcall eclipse-openj9/openj9#15068.](https://github.com/eclipse-openj9/openj9/issues/15068)

Reviewer: @tajila
FYI: @DanHeidinga, @pshipton, @gacholio

**Comment by ChengJin01** [comment]
Updated the code in `PlatformLayouts.java` to support the native functions with variadic arguments in downcall.

**Comment by ChengJin01** [comment]
I just updated the code to enable upcall on s390x/Aarch64/x86 given the java part in PR at https://github.com/eclipse-openj9/openj9/pull/15307 and the native code in https://github.com/eclipse-openj9/openj9/issues/15068 are already merged, in which case the compilation should pass but the code depends on the rest of the PRs in OpenJ9 (especially including the thunk generation code on s390x/Aarch64/x86) listed in https://github.com/eclipse-openj9/openj9/issues/15068 to work.

**Comment by ChengJin01** [comment]
FYI: @knn-k, @dchopra001

**Comment by tajila** [comment]
jenkins test sanity plinux jdk17

**Pull request merged**
