### PR TITLE
Enable JITServer by default on supported platforms

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <dchopra001@gmail.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
@keithc-ca @pshipton Can I get a review please?

**Comment by pshipton** [comment]
Pls enable the rest of the versions (8, 18) earlier this week in order to get them into the M2 build.

**Comment by pshipton** [comment]
> Pls enable the rest of the versions (8, 18) earlier this week in order to get them into the M2 build.

I should have finished checking my email before making that comment. I see 18, 19 already. Pls do 8, which is a little trickier.

**Comment by dchopra001** [comment]
I just opened the Java 8 PR here. It was a bit different. Please let me know if I missed anything: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/579

**Comment by keithc-ca** [comment]
jenkins compile xlinux jdk17

**Pull request merged**
