### PR TITLE
Removed unused scripts

### PR DESCRIPTION
**Pull request by keithc-ca**
The jenkins jobs are configured to use the jdknext repository.

### CODE REVIEW

**Comment by keithc-ca** [comment]
> Are you planning to remove unused scripts every time we branch for a new release?

We can either do that, or move the scripts to another repo that isn't affected by branching; they could even move to the openj9 repo.

**Comment by pshipton** [comment]
I'm not convinced they belong in OpenJ9, since they are checking the extensions code and following IBM rules. Maybe a comment in the head stream that explains the script it only used from the head stream. I expect we could create a new ibmruntimes repo to hold them if desired, but seems overkill.

**Comment by keithc-ca** [comment]
Yes, perhaps OpenJ9 is an inappropriate place, and I agree that a new repo feels like overkill, so I guess we're left with a cleanup job after each major version branch.

**Comment by AdamBrousseau** [comment]
I think @JasonFengJ9 took over creating new repos. Perhaps it's an easy addition to the script to remove this dir at the time of creation. In the meantime, I will merge these PRs.

**Review by AdamBrousseau — APPROVED** [review]

**Pull request merged**
