### PR TITLE
Fix crash in native crypto on concurrent Cipher object use with GCM

### PR DESCRIPTION
**Pull request by samasri**
This PR is the adaptation of ibmruntimes/openj9-openjdk-jdk16#66 for this JDK version

Signed-off-by: Samer Almasri <samasri@ibm.com>

### CODE REVIEW

**Review by keithc-ca — CHANGES_REQUESTED** [review]
I don't think there's a need for either file to be different relative to the corresponding files from jdk16.

**Comment by samasri** [comment]
Are you suggesting I copy the files as is from JDK16?

**Comment by keithc-ca** [comment]
Yes, I suggest you start with the same content as jdk16, only adjusting as necessary.

**Comment by pshipton** [comment]
@samasri is there an ETA for when the problems can be fixed so this and the equivalent PR for other versions can be merged?

**Comment by samasri** [comment]
Hi Peter, I switched to a new team few months ago and I'm not having the time to work on this anymore. Please follow up with the runtimes team about it.

**Comment by pshipton** [comment]
@ashbm5 is there somebody else who can be assigned to port https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/66 to the other versions?

**Comment by ashbm5** [comment]
yes assigned @ZainabF92 to port this to jdk17 and jdk next

**Comment by pshipton** [comment]
There were also uncompleted ports created for jdk8 and 11, if it makes sense to port to those versions.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/529
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/529

**Pull request closed without merging**
