### PR TITLE
Enable CRIU by default on Linux on Z

### PR DESCRIPTION
**Pull request by r30shah**

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity zlinux jdk17

**Comment by tajila** [comment]
jenkins test sanity xlinux jdk17

**Comment by tajila** [comment]
@r30shah seems like there werent any criu tests for the xlinux PR builds

**Comment by r30shah** [comment]
> @r30shah seems like there werent any criu tests for the xlinux PR builds

I looked at the sanity.functional build from OpenJ9 PR Builds, and do see there are CRIU tests being executed on xLinux (https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal/285/tapTestReport/)
all are prefixed with `cmdLineTests_*`  .  Are these tests you are talking about?

**Comment by tajila** [comment]
@r30shah my mistake, I meant zlinux

**Pull request merged**
