### PR TITLE
Revert Update Harfbuzz to 7.0.1

### PR DESCRIPTION
**Pull request by pshipton**
Issue https://github.com/eclipse-openj9/openj9/issues/17759

### CODE REVIEW

**Comment by keithc-ca** [comment]
I think this is missing 5ca81bc3fdcaef5e11766b358d154bcec4623cb8 (#191).

**Comment by pshipton** [comment]
Keith said, you can see the changes are missing when comparing against the 0.38 release branch. I cherry picked the change and added it.

**Comment by keithc-ca** [comment]
Jenkins compile aix jdk17 depends eclipse-openj9/openj9#v0.40.0-release eclipse-openj9/openj9-omr#v0.40.0-release

**Comment by keithc-ca** [comment]
The build failed with the all too frequent "Sjavac server failed to initialize: Deadlock condition if locked" problem.

**Comment by pshipton** [comment]
jdk_imageio testing https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2585/

**Comment by pshipton** [comment]
There is a failure with javax/imageio/plugins/shared/ImageWriterCompressionTest.java
```
17:44:14  java.lang.Error: Probable fatal error: No physical fonts found.
17:44:14  	at java.desktop/sun.font.SunFontManager.lambda$getDefaultPhysicalFont$0(SunFontManager.java:1056)
```

Not sure if it's a result of this change, it may be this change has exposed the failure since it couldn't run before.

**Comment by pshipton** [comment]
It may just be a machine issue, we don't normally run these tests on these machines. I'll try the test internally.

**Comment by pshipton** [comment]
The first iteration passed internally, I think the OpenJ9 machines don't have the font installed.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
