### PR TITLE
Add additional checks to NativeECDHKeyAgreement to match upstream

### PR DESCRIPTION
**Pull request by KostasTsiounis**
There are additional checks that are required during the `init` and `doPhase` parts of `ECDH` key agreement. Those checks are already present in the original `ECDHKeyAgreement` class, so they had to be added to the `NativeECDHKeyAgreement` class as well.

Back-ported from: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/788

Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

### CODE REVIEW

**Comment by KostasTsiounis** [comment]
FYI @keithc-ca

**Comment by keithc-ca** [comment]
Jenkins test sanity xlinux jdk17

**Comment by keithc-ca** [comment]
Jenkins test sanity alinux jdk17

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Grinder testing was also successful:
* jdk_security1 - https://openj9-jenkins.osuosl.org/job/Grinder/3617
* jdk_security2 - https://openj9-jenkins.osuosl.org/job/Grinder/3618
* jdk_security3 - https://openj9-jenkins.osuosl.org/job/Grinder/3619

**Pull request merged**
