### PR TITLE
Re-enable FIPS140-3 failures

### PR DESCRIPTION
**Pull request by JinhangZhang**

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@llxia @jasonkatonica As discussed, re-enable update where test ignores were removed in https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/367.

**Comment by JinhangZhang** [comment]
It is in https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/25d1ee81b8a3e0c6ddce3e2049a139b79988fd20/test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt#L929

> @JinhangZhang I noticed `com/sun/jdi/JdwpAttachTest.java.JdwpAttachTest https://github.com/ibmruntimes/openj9-openjdk-jdk17/issues/321 linux-x64,linux-ppc64le,linux-s390x,aix-all` was added in https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/367/files, but it is not in this PR. It is expected?

**Comment by jasonkatonica** [comment]
These updates look reasonable to me.

**Comment by JinhangZhang** [comment]
@JasonFengJ9 Please help to merge

**Review by JasonFengJ9 — APPROVED** [review]

**Pull request merged**
