### PR TITLE
Revert "8307603: [AIX] Broken build after JDK-8307301"

### PR DESCRIPTION
**Pull request by keithc-ca**
See also https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/235.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins compile aix jdk17

**Comment by pshipton** [comment]
This will need to be double delivered to 0.41 as well.

**Comment by pshipton** [comment]
Testing via grinder
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2958

**Comment by pshipton** [comment]
The grinder failed, but not because libfontmanager.so couldn't be loaded.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
