### PR TITLE
[WIP] Enable OpenJDK MHs for OpenJ9 JDK17 by default

### PR DESCRIPTION
**Pull request by fengxue-IS**
Backport of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/308 + https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/309

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by tajila** [comment]
@fengxue-IS https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/29/ has some additional changes, will those be needed as well?

**Comment by tajila** [comment]
also, we will need an equivalent PR in the https://github.com/ibmruntimes/openj9-openjdk-jdk repo

**Comment by pshipton** [comment]
We don't need this change, as it's already delivered to the openj9-staging branch. We'll enable OJDK MH by default by pushing openj9-staging to the openj9 branch.

**Comment by pshipton** [comment]
openj9-staging will be promoted automatically from https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK17-Acceptance/4/ if the testing passes. If there are known problems preventing the promotion I'll promote it manually.

**Comment by pshipton** [comment]
A new test is causing a problem but we'll get this fixed or reverted.
https://github.com/eclipse-openj9/openj9/issues/13108

**Comment by pshipton** [comment]
The build isn't finished, but note there are still many test failures.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/1/

**Comment by fengxue-IS** [comment]
I've looked at the sanity.openjdk failures in https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/1/ I don't see anything that is related to OpenJDK MH being enabled

`JVMJ9VM007W Command-line option unrecognised: -Xlog:all=warning:stdout` :
java/lang/ProcessBuilder/Basic.java#id0
java/lang/ProcessBuilder/Basic.java#id1

`JVMJ9VM007E Command-line option unrecognised: --enable-native-access=` : https://github.com/eclipse-openj9/openj9/issues/13088
java/foreign/TestFree.java
java/foreign/TestUnsupportedPlatform.java

`Assert_JCL_unimplemented - Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0` https://github.com/eclipse-openj9/openj9/pull/12857
java/foreign/TestResourceScope.java
java/foreign/TestSegmentAllocators.java
java/foreign/channels/TestAsyncSocketChannels.java
java/foreign/channels/TestSocketChannels.java

`java.lang.RuntimeException: 'WARNING: A terminally deprecated method in java.lang.System has been called' missing from stderr`
java/lang/System/SecurityManagerWarnings.java

`Error. Agent error: java.lang.Exception: Agent 3 timed out with a timeout of 960 seconds;`
java/lang/annotation/LoaderLeakTest.java

**Incorrect return value**
java/util/Random/RandomTestBsi1999.java
java/util/Random/RandomTestChiSquared.java

**Comment by pshipton** [comment]
I don't see any of the java/foreign failures in the last jdk17 nightly build from July 2.
job/Test_openjdk17_j9_sanity.openjdk_s390x_linux/38

**Comment by fengxue-IS** [comment]
I think those test are only in the staging branch, newly added in recent jcl level?

**Comment by pshipton** [comment]
Could be. We'll have to take these additional failures into consideration for promoting openj9-staging / enabling OJDK MH. Maybe I shouldn't have been so hasty to close this, it may be another option to enable OJDK MH without taking the openj9-staging content. I'll reopen, and try some PR testing for this tomorrow.

**Comment by pshipton** [comment]
jenkins test sanity,sanity.openjdk zlinux jdk17

**Comment by pshipton** [comment]
Enabling OJDK MH without openj9-staging doesn't work
```
16:25:49      T extends Object declared in class SoftReference
16:25:49  /home/jenkins/workspace/Build_JDK17_s390x_linux_Personal/build/linux-s390x-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:402: error: method join in class String cannot be applied to given types;
16:25:49  		return String.join(prefix, suffix, delimiter, elements, size);
16:25:49  		             ^
16:25:49    required: CharSequence,CharSequence[]
16:25:49    found:    String,String,String,String[],int
16:25:49    reason: varargs mismatch; String[] cannot be converted to CharSequence
16:25:49  /home/jenkins/workspace/Build_JDK17_s390x_linux_Personal/build/linux-s390x-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:406: error: cannot find symbol
16:25:49  		return mod.implIsEnableNativeAccess();
16:25:49  		          ^
16:25:49    symbol:   method implIsEnableNativeAccess()
16:25:49    location: variable mod of type Module
16:25:49  /home/jenkins/workspace/Build_JDK17_s390x_linux_Personal/build/linux-s390x-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:410: error: cannot find symbol
16:25:49  		Module.implAddEnableNativeAccessAllUnnamed();
16:25:49  		      ^
16:25:49    symbol:   method implAddEnableNativeAccessAllUnnamed()
16:25:49    location: class Module
16:25:49  /home/jenkins/workspace/Build_JDK17_s390x_linux_Personal/build/linux-s390x-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:414: error: cannot find symbol
16:25:49  		return mod.implAddEnableNativeAccess();
16:25:49  		          ^
16:25:49    symbol:   method implAddEnableNativeAccess()
16:25:49    location: variable mod of type Module
16:25:49  /home/jenkins/workspace/Build_JDK17_s390x_linux_Personal/build/linux-s390x-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:421: error: method does not override or implement a method from a supertype
16:25:49  	@Override
16:25:49  	^
```

**Comment by tajila** [comment]
The JIT team have reported that eliminating transitions to the interpreter address majority of the perf regressions seen with ojdk mh. This leaves the functional issues as the remaining blockers to enabling ojdk_mh

**Comment by tajila** [comment]
Re-ran sanity.functional: https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_OpenJDK17/6/tapResults/

**Comment by tajila** [comment]
Re-ran sanity.openjdk: https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_OpenJDK17/3/#showFailuresLink

failures are:
```
    java/lang/invoke/VarHandles/VarHandleTestAccessFloat.java.VarHandleTestAccessFloat
    java/lang/invoke/VarHandles/VarHandleTestAccessString.java.VarHandleTestAccessString
    java/util/TimeZone/Bug8149452.java.Bug8149452
    java/lang/invoke/VarHandles/VarHandleTestAccessLong.java.VarHandleTestAccessLong
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/lang/ProcessBuilder/Basic.java#id1.Basic_id1
    java/lang/ProcessBuilder/Basic.java#id1.Basic_id1
    java/lang/System/SecurityManagerWarnings.java.SecurityManagerWarnings
    java/lang/System/SecurityManagerWarnings.java.SecurityManagerWarnings
    java/lang/annotation/LoaderLeakTest.java.LoaderLeakTest
    java/lang/annotation/LoaderLeakTest.java.LoaderLeakTest
    java/util/Random/RandomTestChiSquared.java.RandomTestChiSquared
```

**Comment by tajila** [comment]
The following are being tracked in https://github.com/eclipse-openj9/openj9/issues/13127

```
    java/lang/invoke/VarHandles/VarHandleTestAccessFloat.java.VarHandleTestAccessFloat
    java/lang/invoke/VarHandles/VarHandleTestAccessString.java.VarHandleTestAccessString
    java/lang/invoke/VarHandles/VarHandleTestAccessLong.java.VarHandleTestAccessLong
```

**Comment by tajila** [comment]
Security manager issues being tracked in https://github.com/eclipse-openj9/openj9/issues/12760

**Comment by tajila** [comment]
I've opened exclude PRs for 

```
    java/lang/annotation/LoaderLeakTest.java.LoaderLeakTest
    java/lang/annotation/LoaderLeakTest.java.LoaderLeakTest
    java/util/Random/RandomTestChiSquared.java.RandomTestChiSquared
```

`java/util/TimeZone/Bug8149452.java.Bug8149452` looked like a network issue

**Comment by tajila** [comment]
Once the failures are addressed/excluded I want to re-spin the acceptance build. Any objections @pshipton ?

**Comment by pshipton** [comment]
No objection. I've added sanity.openjdk to the acceptance build. It wasn't running because of the number of failures and artifacts produced. The acceptance build isn't currently set up to promote, would you like me to enable automatic promotion of a green build @tajila ? Although if any known intermittent failure block promotion it can still be done manually.

**Comment by pshipton** [comment]
Note the CloseScope0Tests failure is still going to cause the build to fail. https://github.com/eclipse-openj9/openj9/issues/13195

**Comment by tajila** [comment]
> Note the CloseScope0Tests failure is still going to cause the build to fail. eclipse-openj9/openj9#13195

We will have to temporarily exclude that test, there is an incompatible JCL change between whats in the staging branch and whats in the openj9 branch

**Comment by tajila** [comment]
> The acceptance build isn't currently set up to promote, would you like me to enable automatic promotion of a green build @tajila ?

Yes, please.

**Comment by pshipton** [comment]
Any future green jdk17 acceptance build will automatically promote. If the build fails with known issues, as it often does, such as the pltest failure on zlinux, you can manually promote by pushing the openj9-staging branch to the openj9 branch. This must be a fast forward. Occasionally the openj9-staging branch is out of date and doesn't have the latest changes if something was recently merged to the openj9 branch. Then you can merge the openj9 branch to openj9-staging, and then push openj9-staging to openj9.

**Comment by pshipton** [comment]
Note there was a new level jdk-17+31 yesterday, and this is merged to openj9-staging and a new acceptance build for this started. https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK17-Acceptance/8/

**Comment by pshipton** [comment]
For the moment I've set the default options in the jdk17 acceptance build NOT to promote.

The other test suites need to be evaluated before promoting, even if all the failures are excluded in order to get sanity.functional and sanity.openjdk green. There are quite a few failures in the special.system tests for jdk16 as a result of enabling OJDK MH (i.e. https://openj9-jenkins.osuosl.org/job/Pipeline-Special-System-JDK16/8/), and I'm not sure where we stand for the other jdk17 suites extended.functional, sanity/extended.system. The last set of performance data I saw in Slack still has some big performance regressions in some of the categories, and Dan was concerned about promoting (enabling OJDK MH) with the regressions.

**Comment by keithc-ca** [comment]
I suggest this is no longer relevant since the `--enable-openjdk-methodhandles` configure option was removed by #35.

**Pull request closed without merging**
